version: '3.8'

services:
  odoo:
    build:
      context: .
      dockerfile: Dockerfile # ← Dùng Dockerfile tùy chỉnh
    container_name: odoo16
    depends_on:
      - db
    ports:
      - '8069:8069'
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./extra-addons:/mnt/extra-addons

  db:
    image: postgres:13
    container_name: odoo16-dbv1
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: odoodb16v1
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  odoo-data:
  db-data:
