from . import hr_attendance_payroll
from . import hr_payslip_report
from . import payslip_attendance
from . import generate_salary_wizard
from . import account_analytic_line
from . import hr_payslip
from . import custom_invoice
from . import custom_duration_timeoff
from . import auto_generate_payslip
from . import update_rate_fallback
from . import full_monthly_fix_price
from . import work_saturday_schedule
from . import hr_employee_extension
from . import hr_employee_public
from . import hr_leave_extension
